name = "ErrorMetrics"
uuid = "c324fbf6-076a-4da5-8ad2-21081a6b285c"
version = "0.1.0"
authors = ["SINDBAD Contributors <sindbad@bgc-jena.mpg.de>"]

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34.9"
