name = "Sindbad"
uuid = "36c3e672-7dee-4606-99b5-7e5d8d85a313"
authors = ["SINDBAD Contributors <sindbad@bgc-jena.mpg.de>"]
version = "0.1.0"
description = "Modelâ€“data integration framework for terrestrial ecosystem models (SINDBAD)"
license = "EUPL-1.2"
readme = "README.md"
repository = "https://github.com/LandEcosystems/Sindbad"

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ErrorMetrics = "c324fbf6-076a-4da5-8ad2-21081a6b285c"
FIGlet = "3064a664-84fe-4d92-92c7-ed492f3d8fae"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
OmniTools = "202e6067-a2be-48c9-bc21-3d3d20912f89"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SindbadTEM = "6686e6de-2010-4bf8-9178-b2bcc470766e"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
TimeSamplers = "a27efc82-29b7-4223-84cd-12fc64c7a5bb"
YAXArrayBase = "90b8fcef-0c2d-428d-9c56-5f86629e9d14"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"

[weakdeps]
CMAEvolutionStrategy = "8d3b24bd-414e-49e0-94fb-163cc3a3e411"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Evolutionary = "86b6b26d-c046-49b6-aa0b-5f0f74682bd6"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
PolyesterForwardDiff = "98d1487c-24ca-40b6-b7ab-df2af84e126b"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
SindbadCMAEvolutionStrategyExt = "CMAEvolutionStrategy"
SindbadDifferentialEquationsExt = "DifferentialEquations"
SindbadEnzymeExt = "Enzyme"
SindbadFiniteDiffExt = "FiniteDiff"
SindbadFiniteDifferencesExt = "FiniteDifferences"
SindbadForwardDiffExt = "ForwardDiff"
SindbadNLsolveExt = "NLsolve"
SindbadOptimizationExt = "Optimization"
SindbadPreallocationToolsExt = "PreallocationTools"
SindbadZygoteExt = "Zygote"

[compat]
AxisKeys = "0.2"
CSV = "0.10"
ComponentArrays = "0.15"
ConstructionBase = "1"
DimensionalData = "0.29"
ErrorMetrics = "0.1.0"
FiniteDiff = "2.29.0"
FIGlet = "0.2"
FillArrays = "1"
Flux = "0.16.7"
Infiltrator = "1"
JLD2 = "0.6"
JSON = "1"
NCDatasets = "0.14"
NaNStatistics = "0.6"
NetCDF = "0.12.2"
OmniTools = "0.1.0"
Plots = "1"
ProgressMeter = "1"
SindbadTEM = "0.1.0"
StableRNGs = "1"
StatsBase = "0.34"
ThreadPools = "2"
TimeSamplers = "0.1.0"
YAXArrayBase = "0.7"
YAXArrays = "0.7"
Zarr = "0.9"
julia = "1.10, 1.11"

# Optional dependencies (extensions)
# Keeping these compat entries explicit improves JuliaRegistries AutoMerge compatibility.
CMAEvolutionStrategy = "0.3"
DifferentialEquations = "7"
Enzyme = "0.13"
Evolutionary = "0.11"
FiniteDifferences = "0.12"
ForwardDiff = "0.10"
GlobalSensitivity = "2"
NLopt = "1"
NLsolve = "4"
Optimisers = "0.4"
Optimization = "4"
PolyesterForwardDiff = "0.1"
PreallocationTools = "0.4"
QuasiMonteCarlo = "0.3"
Zygote = "0.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
