[deps]
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Sindbad = "6686e6de-2010-4bf8-9178-b2bcc470766e"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[sources]
Sindbad = {path = "../../"}
SindbadTEM = {path = "../../SindbadTEM"}