[deps]
AbstractDifferentiation = "c29ec348-61ec-40c8-8164-b8c60e9d9f3d"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CMAEvolutionStrategy = "8d3b24bd-414e-49e0-94fb-163cc3a3e411"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GCMAES = "4aa9d100-eb0f-11e8-15f1-25748831eb3b"
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolyesterForwardDiff = "98d1487c-24ca-40b6-b7ab-df2af84e126b"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Sindbad = "36c3e672-7dee-4606-99b5-7e5d8d85a313"
SindbadTEM = "6686e6de-2010-4bf8-9178-b2bcc470766e"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
Sindbad = {path = "../.."}
