[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AutomaticDocstrings = "70b36510-7dee-11e9-28d4-77afe9445f67"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Sindbad = "6686e6de-2010-4bf8-9178-b2bcc470766e"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"