[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
SindbadTEM = "6686e6de-2010-4bf8-9178-b2bcc470766e"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Sindbad = "36c3e672-7dee-4606-99b5-7e5d8d85a313"

[sources]
Sindbad = {path = "../.."}