[deps]
CMAEvolutionStrategy = "8d3b24bd-414e-49e0-94fb-163cc3a3e411"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GCMAES = "4aa9d100-eb0f-11e8-15f1-25748831eb3b"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Sindbad = "6686e6de-2010-4bf8-9178-b2bcc470766e"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[sources]
Sindbad = {path = "../.."}
SindbadTEM = {path = "../../SindbadTEM"}