[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
Sindbad = "36c3e672-7dee-4606-99b5-7e5d8d85a313"
SindbadTEM = "6686e6de-2010-4bf8-9178-b2bcc470766e"

[sources]
Sindbad = {path = "../"}
SindbadTEM = {path = "../SindbadTEM"}
